<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\HyvaCsp;

// phpcs:disable Generic.Files.LineLength

/** @var Escaper $escaper */
/** @var Template $block */
/** @var HyvaCsp $hyvaCsp */

?>
<script>
    (() => {
        if (hyva && hyva.formValidation) {
            const houseNumberContainsNumber = (postcode) => {
                const regex = /\d/;
                return regex.test(postcode);
            }

            hyva.formValidation.addRule('validate-housenumber', (value, options, field, context) => {
                const el = field.element;
                if (options && el.value.length) {
                    if (! houseNumberContainsNumber(el.value)) {
                        return '<?= $escaper->escapeJs(__('Oops! That doesn\'t seem like a valid housenumber. Please try again.')) ?>';
                    }
                }
                return true;
            });
        }
    })()
</script>
<?php $hyvaCsp->registerInlineScript() ?>
